name: edtest
favicon: null
layout_spectrum: 0.10412063612602651
typography_spectrum: 0.6762593586463481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.22334562125615776
  lightness: 0.33328448748216033
  saturation: 0.13286367477849126
  rhythmicContrast: 0.8122153859585524
purpose: []
